export const TEAM_MANAGERS_DETAILS = [
  {
    name: "Sanket Agarwal",
    img: "./images/team/managers/sanket.JPG",
    linkedin: "https://www.linkedin.com/in/sanket-agarwal-5ba719285/",
    facebook: "https://www.facebook.com/profile.php?id=100075516520476",
    mail: "sanketagarwal.teamkartkgp@gmail.com",
    designation1: "Team Leader",
    designation2: "Drivetrain and Thermals Head",
    designation3: "",
  },
  {
    name: "Gokul R",
    img: "./images/team/managers/gokul.JPG",
    linkedin: "https://www.linkedin.com/in/gokulr007/",
    facebook: "https://www.facebook.com/profile.php?id=100074874957923",
    mail: "gokul.teamkartkgp@gmail.com",
    designation1: "Deputy Team Leader",
    designation2: "Modelling and Simulations Head",
    designation3: "",
  },
  {
    name: "Aryan Verma",
    img: "./images/team/managers/Verma.png",
    linkedin: "https://www.linkedin.com/in/aryan-verma-5a4883284/",
    facebook: "https://www.facebook.com/profile.php?id=100013802584124",
    mail: "aryanverma.teamkartkgp@gmail.com",
    designation1: "Finance Head",
    designation2: "",
    designation3: "",
  },
];

export const TECHNICAL_MANAGERS_DETAILS = [
  {
    name: "Nakul Nilange",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/nakul-nilange-719551280/",
    facebook: "https://www.facebook.com/profile.php?id=100013802584124",
    mail: "nakul.teamkartkgp@gmail.com",
    designation1: "Head of Electrical Systems",
    designation2: "Battery and Powertrain Head",
    designation3: "",
  },
  {
    name: "Aditya Varghese",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/nakul-nilange-719551280/",
    facebook: "https://www.facebook.com/profile.php?id=100013802584124",
    mail: "adityav.teamkartkgp@gmail.com",
    designation1: "Head of Mechanical Systems",
    designation2: "Drivetrain and Thermals Head",
    designation3: "",
  },
];


export const TEAM_HEADS_DETAILS = [
  {
    name: "Trideshvaran Bharathi",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/tridesh/",
    facebook: "https://www.facebook.com/profile.php?id=100074065076841",
    mail: "tridesh.teamkartkgp@gmail.com",
    designation1: "Embedded Systems and Controls Head",
    designation2: "",
  },
  {
    name: "Syed Nasif Hossain",
    img: "./images/team/heads/nasif.png",
    linkedin: "https://www.linkedin.com/in/syed-nasif-hossain/",
    facebook: "https://www.facebook.com/avi.saraf.90",
    mail: "nasif.teamkartkgp@gmail.com",
    designation1: "Embedded Systems and Controls Head",
    designation2: "",
  },
  {
    name: "Sanjay Jayaraman",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/sanjay-jayaraman/",
    facebook: "https://www.facebook.com/mayukh.s.saha.404",
    mail: "sanjay.teamkartkgp@gmail.com",
    designation1: "Embedded Systems and Controls Head",
    designation2: "",
  },
  {
    name: "S K Avinash Pranao",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/avinash-pranao-s-k-57b40b2a2/",
    facebook: "https://www.facebook.com/gysndp1",
    mail: "avinashpranao.teamkartkgp@gmail.com",
    designation1: "Data Acquisition System Head",
    designation2: "",
  },
  { name: "Aryan Sanghariyat",
    img: "./images/team/heads/sang.png",
    linkedin: "https://www.linkedin.com/in/aryan-sanghariyat-46a4a0282/",
    facebook: "--",
    mail: "aryansanghariyat.teamkartkgp@gmail.com",
    designation1: "Battery and Powertrain Head",
    designation2: "",
  },
  {
    name: "Rhythm Jain",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/rhythm-jain-9a5939203/",
    facebook: "https://www.facebook.com/profile.php?id=100075757830008",
    mail: "rhythmjain.teamkartkgp@gmail.com",
    designation1: "Battery and Powertrain Head",
    designation2: "",
  },
  {
    name: "Akhil Vasan K R",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/akhil-vasan-k-r-243392284/",
    facebook: "https://www.facebook.com/profile.php?id=100095276090541",
    mail: "akhilvasan.teamkartkgp@gmail.com",
    designation1: "Battery and Powertrain Head",
    designation2: "",
  },
  {
    name: "Nishant Kumar",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/nishant-kumar-03b0a8203/",
    facebook: "https://www.facebook.com/profile.php?id=100074420423605",
    mail: "nishantkumar.teamkartkgp@gmail.com",
    designation1: "Corporate Relations and Events Head",
    designation2: "",
  },
  {
    name: "BA. Pranavi",
    img: "./images/team/members/avatar.png",
    linkedin: "www.linkedin.com/in/ba-pranavi/",
    facebook: "https://www.facebook.com/PranaviBA",
    mail: "pranavi.teamkartkgp@gmail.com",
    designation1: "Aerodynamics & Composites Head",
    designation2: "",
  },
  {
    name: "Harsh Modi",
    img: "./images/team/heads/harsh.jpg",
    linkedin: "https://www.linkedin.com/in/harsh-modi-33a111284/",
    facebook: "https://www.facebook.com/harsh.modi.545/about_overview",
    mail: "harshmodi.teamkartkgp@gmail.com",
    designation1: "Suspension, Steering & Brakes Head",
    designation2: "Aerodynamics & Composites Head",
  },
  {
    name: "Akshar Garg",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/akshar-garg-366805280/",
    facebook: "https://www.facebook.com/akshar.garg.77",
    mail: "akshargarg.teamkartkgp@gmail.com",
    designation1: "Suspension, Steering & Brakes Head",
    designation2: "",
  },
  {
    name: "Saarisht Naveen Kalra",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/saarishtkalra?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    facebook: "",
    mail: "saarishtkalra.teamkartkgp@gmail.com",
    designation1: "Suspension, Steering & Brakes Head",
    designation2: "",
  },
  {
    name: "Rajvardhan Padghan",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/rajvardhan-padghan-170b0027b/",
    facebook: "",
    mail: "rajvardhanpadghan.teamkartkgp@gmail.com",
    designation1: "Suspension, Steering & Brakes Head",
    designation2: "",
  },
  {
    name: "Govind Bhat",
    img: "./images/team/members/avatar.png",
    linkedin:"https://www.linkedin.com/in/govind-bhat-b24370238",
    facebook: "https://www.facebook.com/share/16pQcbGHxb/",
    mail: "govindbhat.teamkartkgp@gmail.com",
    designation1: "Drivetrain & Thermals Head",
    designation2: "",
  },
  {
    name: "Priyavrat Mohta",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/priyavrat-mohta-332a83268",
    facebook: "https://www.facebook.com/profile.php?id=100075404450770",
    mail: "priyavratmohta.teamkartkgp@gmail.com",
    designation1: "Chassis Head",
    designation2: "",
  },
  {
    name: "Aryaan Sinha",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/aryaansinha/",
    facebook: "https://www.facebook.com/profile.php?id=100094031314693",
    mail: "aryaansinha.teamkartkgp@gmail.com",
    designation1: "Chassis Head",
    designation2: "",
  },
  {
    name: "Annamalai T V",
    img: "./images/team/members/avatar.png",
    linkedin: "https://www.linkedin.com/in/annaamalai-t-vanmeeganathan-25684b291/",
    facebook: "",
    mail: "annaamalai.vanmeeganathan@gmail.com",
    designation1: "Media and Public Relations Head",
    designation2: "",
  },
];



export const TEAM_MEMBERS_DETAILS = [
  {
    name: "Aakarsh A",
    subsystem: "Electronics",
  },
  {
    name: "Abhinandh",
    subsystem: "Electronics",
  },
  {
    name: "Aniket Thakare",
    subsystem: "Media & Corporate and Public Relations",
  },
  {
    name: "Aniruddha Ghosh",
    subsystem: "Mechanical",
  },
  {
    name: "Anirudha Wasnik",
    subsystem: "Mechanical",
  },
  {
    name: "Ayush Saraykar",
    subsystem: "Mechanical",
  },
  {
    name: "Deep Ghosh",
    subsystem: "ABC",
  },
  {
    name: "Dev Bhatia",
    subsystem: "ABC",
  },
  {
    name: "Disha Uppuluri",
    subsystem: "ABC",
  },
  {
    name: "Disha Uppuluri",
    subsystem: "ABC",
  },
  {
    name: "Himanshu Sahu",
    subsystem: "ABC",
  },
  {
    name: "Himanshu Singh",
    subsystem: "ABC",
  },
  {
    name: "Jaya Shankar",
    subsystem: "ABC",
  },
  {
    name: "K Aniruddha Bhardwaj",
    subsystem: "ABC",
  },
  {
    name: "Kislay Arya",
    subsystem: "ABC",
  },
  {
    name: "Kunal Kathuria",
    subsystem: "ABC",
  },
  {
    name: "Oishik Nandi",
    subsystem: "ABC",
  },
  {
    name: "Pritish Saha",
    subsystem: "ABC",
  },
  {
    name: "Roctotpal Sandilya",
    subsystem: "ABC",
  },
  {
    name: "Samarth Rane",
    subsystem: "ABC",
  },
  {
    name: "Sanskar Agarwal",
    subsystem: "ABC",
  },
  {
    name: "Sarthak Tonk",
    subsystem: "ABC",
  },
  {
    name: "Shubham Pingale",
    subsystem: "ABC",
  },
  {
    name: "Srinjoy Ganguly",
    subsystem: "ABC",
  },
  {
    name: "Thejaswini Devakumar",
    subsystem: "ABC",
  },
  {
    name: "Vaibhav K",
    subsystem: "ABC",
  },
];
